DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Profile;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS ChatRoom;
DROP TABLE IF EXISTS ChatMessage;

CREATE TABLE User (
  userId INTEGER PRIMARY KEY AUTOINCREMENT,
  fullName TEXT NOT NULL,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  profileImage TEXT NOT NULL,
  sendNotification BOOLEAN
);

CREATE TABLE Event (
  eventId INTEGER PRIMARY KEY AUTOINCREMENT,
  eventName TEXT NOT NULL,
  userId INTEGER NOT NULL,
  description TEXT NOT NULL,
  tags TEXT NOT NULL,
  participants TEXT,
  favorites TEXT,
  type TEXT NOT NULL,
  zoomLink TEXT NOT NULL,
  eventImage TEXT NOT NULL,
  date TEXT NOT NULL,
  numParticipate INTEGER NOT NULL
);

CREATE TABLE Profile (
  profileId INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  tags TEXT,
  followers TEXT,
  following TEXT
);

CREATE TABLE Notification (
  notificationId INTEGER PRIMARY KEY AUTOINCREMENT,
  recipientId INTEGER NOT NULL,
  type TEXT NOT NULL,
  date TEXT NOT NULL,
  eventId INTEGER,
  userId INTEGER,
  groupId INTEGER
);

CREATE TABLE UserChat (
  roomId INTEGER PRIMARY KEY AUTOINCREMENT,
  user1 INTEGER NOT NULL,
  user2 INTEGER NOT NULL
);

CREATE TABLE GroupChat (
  roomId INTEGER PRIMARY KEY AUTOINCREMENT,
  groupId INTEGER NOT NULL
);

CREATE TABLE ChatMessage (
  messageId INTEGER PRIMARY KEY AUTOINCREMENT,
  roomId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  message TEXT NOT NULL,
  chatType INTEGER, /* 0 for user_chat, 1 for group_chat*/
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);